#!/bin/bash

# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

#PS1='\[[\u@ \e[1;31m\]\h \e[0;37m\W]\$\[\e[0m\] '

echo "USER" ${USER}
echo "\$(logname)" $(logname)
echo "\$LOGNAME" $LOGNAME
echo "uname -mrs:" `uname -mrs`

case $HOSTNAME in
    "zueub"[2-4][0-9][0-9])
	if [ -d /opt/users/$LOGNAME/monti-pytroll/ ]
        then
            source /opt/users/$LOGNAME/monti-pytroll/setup/set_paths.sh
        else
            source /opt/users/$LOGNAME/PyTroll/setup/set_paths.sh
        fi
	;;
    "keschln-"[0-9][0-9][0-9][0-9])
        # tmp !!!! BAD DIRTY FIX !!!!
        export LOGNAME_ORG=$LOGNAME
        export LOGNAME=hamann
	source /users/hamann/monti-pytroll/setup/set_paths.sh  # load functions from this script
	;;
    *)
	echo "ERROR in setup/bashrc: unknown computer "$HOSTNAME
	return ;;
	#exit 1 ;;
esac

cd $PYTROLLHOME
set_utils_path
set_conda_path
set_pytroll_paths

case $HOSTNAME in
"zueub"[2-4][0-9][0-9])
    # special settings only for zueub computers
    alias tkdiff='echo tkdiff is too old, use \"meld\" instead; echo  meld '
    export http_proxy=http://proxy.meteoswiss.ch:8080
    export https_proxy=https://proxy.meteoswiss.ch:8080
    export XAUTHORITY=/home/lom/users/$LOGNAME/.Xauthority
    export FULLNAME=`getent passwd $LOGNAME | cut -d ":" -f 5 | cut -d "," -f 1`
    export FIRSTNAME=`echo $FULLNAME | cut -d " " -f 1`
    export LASTNAME=`echo $FULLNAME | cut -d " " -f 2`
    export EMAIL=${FIRSTNAME}.${LASTNAME}@meteoswiss.ch
    #if [ -f /usr/bin/tkdiff ]
    #then
    #	echo "...use /usr/bin/tkdiff"
    #else
    #	echo "...use /opt/users/common/packages/tkdiff-unix/tkdiff"
    #	alias tkdiff='/opt/users/common/packages/tkdiff-unix/tkdiff'
    #fi
    ;;
"keschln-"[0-9][0-9][0-9][0-9])
    ;;
*)
    echo "ERROR in bashrc: unknown computer "$HOSTNAME
    return
    ;;
esac

#export PY_SHAPEFILES=$PYTROLLHOME/shapes/

export PYTHONPATH=$CONDA_PATH/bin:$PYTROLLHOME/scripts

# activate virtual environment
source activate PyTroll_$LOGNAME

# some useful alias commands
alias ll='ls --color=auto -alh'
alias ls='ls --color=auto'

# tmp !!!! BAD DIRTY FIX !!!!
case $HOSTNAME in
    "keschln-"[0-9][0-9][0-9][0-9])
	export LOGNAME=$LOGNAME_ORG
	;;
esac